// Generated from the Te Araroa Trust 2026-27 season GPX (Section Routes) and KMZ (Google Earth) downloads,
// cross-referenced during the architecture-review data audit. See conversation history for method.
// Do not hand-edit distance/km/status values without re-deriving from the source files.

import type { OfficialSectionSeed, RegionSeed, SectionRegionSeed } from './officialSections2026_27.types';

export const TRUST_SEASON = '2026-27';

export const REGION_SEEDS: RegionSeed[] = [
  { id: 'northland', name: "Northland", sequence: 1, island: 'NI' },
  { id: 'auckland', name: "Auckland", sequence: 2, island: 'NI' },
  { id: 'waikato', name: "Waikato", sequence: 3, island: 'NI' },
  { id: 'whanganui', name: "Whanganui", sequence: 4, island: 'NI' },
  { id: 'manawatu', name: "Manawatū", sequence: 5, island: 'NI' },
  { id: 'wellington', name: "Wellington", sequence: 6, island: 'NI' },
  { id: 'marlborough', name: "Marlborough", sequence: 7, island: 'SI' },
  { id: 'tasman', name: "Tasman", sequence: 8, island: 'SI' },
  { id: 'canterbury', name: "Canterbury", sequence: 9, island: 'SI' },
  { id: 'otago', name: "Otago", sequence: 10, island: 'SI' },
  { id: 'southland', name: "Southland", sequence: 11, island: 'SI' },
];

export const SECTION_SEEDS: OfficialSectionSeed[] = [
  {
    id: 'te-araroa-01',
    officialNumber: 1,
    officialName: "Cape Reinga to Ahipara",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 101.2,
    cumulativeFromKm: 0,
    cumulativeToKm: 101.2,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-02',
    officialNumber: 2,
    officialName: "The Northland Forests",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 98.03,
    cumulativeFromKm: 101.2,
    cumulativeToKm: 199.2,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-03',
    officialNumber: 3,
    officialName: "Omahuta-Puketi Wet Weather Bypass",
    kind: 'bypass',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: "te-araroa-02",
    matchConfidence: "confirmed",
    officialDistanceKm: 31.4,
    cumulativeFromKm: null,
    cumulativeToKm: null,
    accessStatus: null,
    sourceStatusRaw: "bypass",
    bypassReason: "Wet weather option",
    tidalDependent: false,
  },
  {
    id: 'te-araroa-04',
    officialNumber: 4,
    officialName: "Mangakaretu to Kerikeri",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 26.17,
    cumulativeFromKm: 199.2,
    cumulativeToKm: 225.4,
    accessStatus: "seasonal",
    sourceStatusRaw: "open,Seasonal,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-05',
    officialNumber: 5,
    officialName: "Kerikeri to Waitangi",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 17.47,
    cumulativeFromKm: 225.4,
    cumulativeToKm: 242.9,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-06',
    officialNumber: 6,
    officialName: "Paihia to Opua Coastal Walkway",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 8.96,
    cumulativeFromKm: 242.9,
    cumulativeToKm: 251.8,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-07',
    officialNumber: 7,
    officialName: "Waikare Connection - by Water",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 11.06,
    cumulativeFromKm: 251.8,
    cumulativeToKm: 262.9,
    accessStatus: "open",
    sourceStatusRaw: "water",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-08',
    officialNumber: 8,
    officialName: "Waikare Connection - by Road Bypass",
    kind: 'bypass',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: "te-araroa-07",
    matchConfidence: "confirmed",
    officialDistanceKm: 13.89,
    cumulativeFromKm: null,
    cumulativeToKm: null,
    accessStatus: null,
    sourceStatusRaw: "bypass",
    bypassReason: "Opua Canoe Bypass via Russel Road",
    tidalDependent: false,
  },
  {
    id: 'te-araroa-09',
    officialNumber: 9,
    officialName: "Waikare to Ngunguru",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 85.44,
    cumulativeFromKm: 262.9,
    cumulativeToKm: 348.3,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-10',
    officialNumber: 10,
    officialName: "Ngunguru to Horahora Bypass",
    kind: 'bypass',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: "te-araroa-09",
    matchConfidence: "likely",
    officialDistanceKm: 24.9,
    cumulativeFromKm: null,
    cumulativeToKm: null,
    accessStatus: null,
    sourceStatusRaw: "bypass",
    bypassReason: "Bypass route",
    tidalDependent: false,
  },
  {
    id: 'te-araroa-11',
    officialNumber: 11,
    officialName: "Ngunguru to Pataua North",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 26.3,
    cumulativeFromKm: 348.3,
    cumulativeToKm: 374.6,
    accessStatus: "seasonal",
    sourceStatusRaw: "open,Seasonal,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-12',
    officialNumber: 12,
    officialName: "Pataua North to Whangarei Heads",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 33.86,
    cumulativeFromKm: 374.6,
    cumulativeToKm: 407.3,
    accessStatus: "open",
    sourceStatusRaw: "road,open,water",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-13',
    officialNumber: 13,
    officialName: "Bream Bay Walk",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 27.4,
    cumulativeFromKm: 407.3,
    cumulativeToKm: 434.7,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-14',
    officialNumber: 14,
    officialName: "Cullen Brynderwyn Walkway",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 13.58,
    cumulativeFromKm: 434.7,
    cumulativeToKm: 448.3,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-15',
    officialNumber: 15,
    officialName: "Bream Tail to Mangawhai Cliffs Walkway",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 7.37,
    cumulativeFromKm: 448.3,
    cumulativeToKm: 455.7,
    accessStatus: "seasonal",
    sourceStatusRaw: "Seasonal,open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-16',
    officialNumber: 16,
    officialName: "Mangawhai to Pakiri",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 29.79,
    cumulativeFromKm: 455.7,
    cumulativeToKm: 485.5,
    accessStatus: "open",
    sourceStatusRaw: "road,open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-17',
    officialNumber: 17,
    officialName: "Mt Tamahunga (Te Hikoi O Te Kiri) Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 10.94,
    cumulativeFromKm: 485.5,
    cumulativeToKm: 496.4,
    accessStatus: "open",
    sourceStatusRaw: "road,open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-18',
    officialNumber: 18,
    officialName: "Govan Wilson to Puhoi Valley",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 37.58,
    cumulativeFromKm: 496.4,
    cumulativeToKm: 534,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-19',
    officialNumber: 19,
    officialName: "Puhoi Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 5.13,
    cumulativeFromKm: 534,
    cumulativeToKm: 539.1,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-20',
    officialNumber: 20,
    officialName: "Puhoi Track Bypass",
    kind: 'bypass',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: "te-araroa-19",
    matchConfidence: "confirmed",
    officialDistanceKm: 3.88,
    cumulativeFromKm: null,
    cumulativeToKm: null,
    accessStatus: null,
    sourceStatusRaw: "bypass",
    bypassReason: "Puhoi Track will remain closed for 23-24 season.",
    tidalDependent: false,
  },
  {
    id: 'te-araroa-21',
    officialNumber: 21,
    officialName: "Puhoi to Wenderholm Kayak",
    kind: 'main',
    travelMode: 'kayak',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 7.43,
    cumulativeFromKm: 539.1,
    cumulativeToKm: 546.5,
    accessStatus: "open",
    sourceStatusRaw: "water",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-22',
    officialNumber: 22,
    officialName: "Puhoi to Wenderholm Walk Bypass",
    kind: 'bypass',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: "te-araroa-21",
    matchConfidence: "likely",
    officialDistanceKm: 6.58,
    cumulativeFromKm: null,
    cumulativeToKm: null,
    accessStatus: null,
    sourceStatusRaw: "bypass",
    bypassReason: "Alternative to canoe Puhoi to Waiwera",
    tidalDependent: false,
  },
  {
    id: 'te-araroa-23',
    officialNumber: 23,
    officialName: "Wenderholm to Stillwater",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 26.23,
    cumulativeFromKm: 546.5,
    cumulativeToKm: 572.8,
    accessStatus: "open",
    sourceStatusRaw: "road,open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-24',
    officialNumber: 24,
    officialName: "Okura to Long Bay - Low Tide crossing",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 4.57,
    cumulativeFromKm: 572.8,
    cumulativeToKm: 577.3,
    accessStatus: "open",
    sourceStatusRaw: "open,water",
    bypassReason: null,
    tidalDependent: true,
  },
  {
    id: 'te-araroa-25',
    officialNumber: 25,
    officialName: "North Shore Coastal Walk",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 31.69,
    cumulativeFromKm: 577.3,
    cumulativeToKm: 606,
    accessStatus: "open",
    sourceStatusRaw: "water,open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-26',
    officialNumber: 26,
    officialName: "Coast to Coast Walkway",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 15.72,
    cumulativeFromKm: 606,
    cumulativeToKm: 621.7,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-27',
    officialNumber: 27,
    officialName: "Onehunga to Puhinui",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 22.47,
    cumulativeFromKm: 621.7,
    cumulativeToKm: 644.2,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-28',
    officialNumber: 28,
    officialName: "Puhinui Stream Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 8.89,
    cumulativeFromKm: 644.2,
    cumulativeToKm: 653.1,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-29',
    officialNumber: 29,
    officialName: "Botanic Gardens to Mangatawhiri",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 38.9,
    cumulativeFromKm: 653.1,
    cumulativeToKm: 692,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-30',
    officialNumber: 30,
    officialName: "Mangatawhiri to Mercer",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 13.96,
    cumulativeFromKm: 692,
    cumulativeToKm: 705.9,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-31',
    officialNumber: 31,
    officialName: "Mercer to Rangiriri",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 23.17,
    cumulativeFromKm: 705.9,
    cumulativeToKm: 729.1,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-32',
    officialNumber: 32,
    officialName: "Rangiriri to Huntly",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 21.38,
    cumulativeFromKm: 729.1,
    cumulativeToKm: 750.5,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-33',
    officialNumber: 33,
    officialName: "Hakarimata Walkway",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 12.31,
    cumulativeFromKm: 750.5,
    cumulativeToKm: 762.8,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-34',
    officialNumber: 34,
    officialName: "Ngaruawahia to Hamilton - Te Awa (The River)",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 22.55,
    cumulativeFromKm: 762.8,
    cumulativeToKm: 785.4,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-35',
    officialNumber: 35,
    officialName: "Hamilton City",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 8.51,
    cumulativeFromKm: 785.4,
    cumulativeToKm: 793.9,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-36',
    officialNumber: 36,
    officialName: "Waipa Walk",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 28.29,
    cumulativeFromKm: 793.9,
    cumulativeToKm: 822.2,
    accessStatus: "seasonal",
    sourceStatusRaw: "road,Seasonal,open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-37',
    officialNumber: 37,
    officialName: "Pirongia Traverse",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 16.18,
    cumulativeFromKm: 822.2,
    cumulativeToKm: 838.4,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-38',
    officialNumber: 38,
    officialName: "Pirongia to Waitomo",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 44.77,
    cumulativeFromKm: 838.4,
    cumulativeToKm: 883.1,
    accessStatus: "seasonal",
    sourceStatusRaw: "open,road,Seasonal",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-39',
    officialNumber: 39,
    officialName: "Pehitawa Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 14.77,
    cumulativeFromKm: 883.1,
    cumulativeToKm: 897.9,
    accessStatus: "seasonal",
    sourceStatusRaw: "Seasonal,open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-40',
    officialNumber: 40,
    officialName: "Te Kuiti to Pureora",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 57.55,
    cumulativeFromKm: 897.9,
    cumulativeToKm: 955.4,
    accessStatus: "seasonal",
    sourceStatusRaw: "open,Seasonal,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-41',
    officialNumber: 41,
    officialName: "Pureora Forest - The Timber Trail",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 104.72,
    cumulativeFromKm: 955.4,
    cumulativeToKm: 1060.2,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-42',
    officialNumber: 42,
    officialName: "42 Traverse",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 73.16,
    cumulativeFromKm: 1060.2,
    cumulativeToKm: 1133.3,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-43',
    officialNumber: 43,
    officialName: "42 Traverse Track Bypass",
    kind: 'bypass',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: "te-araroa-42",
    matchConfidence: "confirmed",
    officialDistanceKm: 4.35,
    cumulativeFromKm: null,
    cumulativeToKm: null,
    accessStatus: null,
    sourceStatusRaw: "open",
    bypassReason: "DOC required bypass of slip",
    tidalDependent: false,
  },
  {
    id: 'te-araroa-44',
    officialNumber: 44,
    officialName: "Tongariro Alpine Crossing",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 38.4,
    cumulativeFromKm: 1133.3,
    cumulativeToKm: 1171.7,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-45',
    officialNumber: 45,
    officialName: "Mangatepopo to National Park",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 21.4,
    cumulativeFromKm: 1171.7,
    cumulativeToKm: 1193.1,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-46',
    officialNumber: 46,
    officialName: "National Park to Whanganui River",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 88.73,
    cumulativeFromKm: 1193.1,
    cumulativeToKm: 1281.8,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-47',
    officialNumber: 47,
    officialName: "Whanganui River Whakahoro - Pipiriki Kayak Bypass",
    kind: 'bypass',
    travelMode: 'kayak',
    countsTowardTrailDistance: true,
    relatedSectionId: "te-araroa-48",
    matchConfidence: "confirmed",
    officialDistanceKm: 56.48,
    cumulativeFromKm: null,
    cumulativeToKm: null,
    accessStatus: null,
    sourceStatusRaw: "bypass",
    bypassReason: "Whakahoro to Pipiriki by canoe",
    tidalDependent: false,
  },
  {
    id: 'te-araroa-48',
    officialNumber: 48,
    officialName: "Whanganui River - via Whanganui River",
    kind: 'main',
    // Not caught by the automatic name-based derivation (its own name doesn't
    // contain "kayak"), but confirmed by the KMZ Notes text on its bypasses
    // ("Alternative to canoe...", "Up Whanganui River...") and its own
    // sourceStatusRaw of "open,water" below: this is the canoe/kayak journey
    // down the Whanganui River, the default main route for this section.
    travelMode: 'kayak',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 121.75,
    cumulativeFromKm: 1281.8,
    cumulativeToKm: 1403.6,
    accessStatus: "open",
    sourceStatusRaw: "open,water",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-49',
    officialNumber: 49,
    officialName: "Whanganui River Bypass North (Walking)",
    kind: 'bypass',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: "te-araroa-48",
    matchConfidence: "confirmed",
    officialDistanceKm: 61.3,
    cumulativeFromKm: null,
    cumulativeToKm: null,
    accessStatus: null,
    sourceStatusRaw: "bypass",
    bypassReason: "Up Whanganui River Northbound",
    tidalDependent: false,
  },
  {
    id: 'te-araroa-50',
    officialNumber: 50,
    officialName: "Whanganui River Bypass South (Walking)",
    kind: 'bypass',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: "te-araroa-48",
    matchConfidence: "confirmed",
    officialDistanceKm: 6.52,
    cumulativeFromKm: null,
    cumulativeToKm: null,
    accessStatus: null,
    sourceStatusRaw: "bypass",
    bypassReason: "Up Whanganui River in Whanganui",
    tidalDependent: false,
  },
  {
    id: 'te-araroa-51',
    officialNumber: 51,
    officialName: "Whanganui to Bulls",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 58.47,
    cumulativeFromKm: 1403.6,
    cumulativeToKm: 1462.1,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-52',
    officialNumber: 52,
    officialName: "Bulls to Feilding",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 22.84,
    cumulativeFromKm: 1462.1,
    cumulativeToKm: 1484.9,
    accessStatus: "open",
    sourceStatusRaw: "road,open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-53',
    officialNumber: 53,
    officialName: "Feilding to Palmerston North",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 20.08,
    cumulativeFromKm: 1484.9,
    cumulativeToKm: 1505,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-54',
    officialNumber: 54,
    officialName: "Palmerston North to Poads Road",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 68.2,
    cumulativeFromKm: 1505,
    cumulativeToKm: 1573.2,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-55',
    officialNumber: 55,
    officialName: "Tararua Ranges",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 47.37,
    cumulativeFromKm: 1573.2,
    cumulativeToKm: 1620.6,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-56',
    officialNumber: 56,
    officialName: "Pukeatua Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 26.1,
    cumulativeFromKm: 1620.6,
    cumulativeToKm: 1646.7,
    accessStatus: "open",
    sourceStatusRaw: "road,open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-57',
    officialNumber: 57,
    officialName: "Kapiti Coast",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 21.56,
    cumulativeFromKm: 1646.7,
    cumulativeToKm: 1668.2,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-58',
    officialNumber: 58,
    officialName: "Escarpment Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 10.4,
    cumulativeFromKm: 1668.2,
    cumulativeToKm: 1678.6,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-59',
    officialNumber: 59,
    officialName: "Ara Harakeke (Flax Pathway)",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 13.38,
    cumulativeFromKm: 1678.6,
    cumulativeToKm: 1692,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-60',
    officialNumber: 60,
    officialName: "Rangituhi- Colonial Knob Walk",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 23.16,
    cumulativeFromKm: 1692,
    cumulativeToKm: 1715.2,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-61',
    officialNumber: 61,
    officialName: "Ngaio",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 8.09,
    cumulativeFromKm: 1715.2,
    cumulativeToKm: 1723.2,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-62',
    officialNumber: 62,
    officialName: "Wellington City",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 5.53,
    cumulativeFromKm: 1723.2,
    cumulativeToKm: 1728.8,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-63',
    officialNumber: 63,
    officialName: "Wellington South",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 10.18,
    cumulativeFromKm: 1728.8,
    cumulativeToKm: 1739,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-64',
    officialNumber: 64,
    officialName: "The Interislander Connection",
    kind: 'main',
    travelMode: 'ferry',
    countsTowardTrailDistance: false,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 99.04,
    cumulativeFromKm: 1739,
    cumulativeToKm: 1739,
    accessStatus: "open",
    sourceStatusRaw: "strait",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-65',
    officialNumber: 65,
    officialName: "Picton to Ship Cove - Water Taxi",
    kind: 'main',
    travelMode: 'water_taxi',
    countsTowardTrailDistance: false,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 35.29,
    cumulativeFromKm: 1739,
    cumulativeToKm: 1739,
    accessStatus: "open",
    sourceStatusRaw: "strait",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-66',
    officialNumber: 66,
    officialName: "Queen Charlotte Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 69.6,
    cumulativeFromKm: 1739,
    cumulativeToKm: 1808.6,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-67',
    officialNumber: 67,
    officialName: "Anakiwa to Pelorus Bridge",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 41.62,
    cumulativeFromKm: 1808.6,
    cumulativeToKm: 1850.2,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-68',
    officialNumber: 68,
    officialName: "Pelorus River Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 44.6,
    cumulativeFromKm: 1850.2,
    cumulativeToKm: 1894.8,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-69',
    officialNumber: 69,
    officialName: "Richmond Alpine Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 95.72,
    cumulativeFromKm: 1894.8,
    cumulativeToKm: 1990.5,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-70',
    officialNumber: 70,
    officialName: "Waiau Pass Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 118.89,
    cumulativeFromKm: 1990.5,
    cumulativeToKm: 2109.4,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-71',
    officialNumber: 71,
    officialName: "Lewis Pass Road Bypass",
    kind: 'bypass',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: "te-araroa-70",
    matchConfidence: "likely",
    officialDistanceKm: 11.75,
    cumulativeFromKm: null,
    cumulativeToKm: null,
    accessStatus: null,
    sourceStatusRaw: "bypass",
    bypassReason: "Wet weather bridge at Windy Point",
    tidalDependent: false,
  },
  {
    id: 'te-araroa-72',
    officialNumber: 72,
    officialName: "Boyle to Arthur's Pass",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 115.45,
    cumulativeFromKm: 2109.4,
    cumulativeToKm: 2224.8,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-73',
    officialNumber: 73,
    officialName: "Arthur's Pass to Rakaia River",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 73.47,
    cumulativeFromKm: 2224.8,
    cumulativeToKm: 2298.3,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-74',
    officialNumber: 74,
    officialName: "Rakaia River Hazard Zone Bypass",
    kind: 'bypass',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: "te-araroa-73",
    matchConfidence: "confirmed",
    officialDistanceKm: 61.55,
    cumulativeFromKm: null,
    cumulativeToKm: null,
    accessStatus: null,
    sourceStatusRaw: "bypass",
    bypassReason: "via Rakaia River Bridge",
    tidalDependent: false,
  },
  {
    id: 'te-araroa-75',
    officialNumber: 75,
    officialName: "Rakaia River to Rangitata River",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 69.49,
    cumulativeFromKm: 2298.3,
    cumulativeToKm: 2367.8,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-76',
    officialNumber: 76,
    officialName: "Rangitata River Hazard Zone Bypass",
    kind: 'bypass',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: "te-araroa-75",
    matchConfidence: "confirmed",
    officialDistanceKm: 136.91,
    cumulativeFromKm: null,
    cumulativeToKm: null,
    accessStatus: null,
    sourceStatusRaw: "bypass",
    bypassReason: "Hazard Bypass on remote access roads",
    tidalDependent: false,
  },
  {
    id: 'te-araroa-77',
    officialNumber: 77,
    officialName: "Two Thumb Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 74.43,
    cumulativeFromKm: 2367.8,
    cumulativeToKm: 2442.2,
    accessStatus: "open",
    sourceStatusRaw: "road,open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-78',
    officialNumber: 78,
    officialName: "Tekapo to Lake Ohau",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 86.88,
    cumulativeFromKm: 2442.2,
    cumulativeToKm: 2529.1,
    accessStatus: "open",
    sourceStatusRaw: "open,road",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-79',
    officialNumber: 79,
    officialName: "East Ahuriri Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 25,
    cumulativeFromKm: 2529.1,
    cumulativeToKm: 2554.1,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-80',
    officialNumber: 80,
    officialName: "Breast Hill Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 53.79,
    cumulativeFromKm: 2554.1,
    cumulativeToKm: 2607.9,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-81',
    officialNumber: 81,
    officialName: "Gladstone to Wanaka",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 30.66,
    cumulativeFromKm: 2607.9,
    cumulativeToKm: 2638.6,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-82',
    officialNumber: 82,
    officialName: "Glendhu Bay Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 16.76,
    cumulativeFromKm: 2638.6,
    cumulativeToKm: 2655.3,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-83',
    officialNumber: 83,
    officialName: "Motatapu Alpine Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 48.81,
    cumulativeFromKm: 2655.3,
    cumulativeToKm: 2704.1,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-84',
    officialNumber: 84,
    officialName: "Wakatipu Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 29.64,
    cumulativeFromKm: 2704.1,
    cumulativeToKm: 2733.8,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-85',
    officialNumber: 85,
    officialName: "Lake Wakatipu Hazard Zone Bypass",
    kind: 'bypass',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: "te-araroa-84",
    matchConfidence: "confirmed",
    officialDistanceKm: 80.2,
    cumulativeFromKm: null,
    cumulativeToKm: null,
    accessStatus: null,
    sourceStatusRaw: "bypass",
    bypassReason: "No ferry, use a shuttle to Greenstone head",
    tidalDependent: false,
  },
  {
    id: 'te-araroa-86',
    officialNumber: 86,
    officialName: "Mavora Walkway",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 51.05,
    cumulativeFromKm: 2733.8,
    cumulativeToKm: 2784.8,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-87',
    officialNumber: 87,
    officialName: "Mararoa River Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 45.02,
    cumulativeFromKm: 2784.8,
    cumulativeToKm: 2829.8,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-88',
    officialNumber: 88,
    officialName: "Takitimu Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 75.93,
    cumulativeFromKm: 2829.8,
    cumulativeToKm: 2905.8,
    accessStatus: "seasonal",
    sourceStatusRaw: "Seasonal,open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-89',
    officialNumber: 89,
    officialName: "Birchwood to Merrivale",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 27.12,
    cumulativeFromKm: 2905.8,
    cumulativeToKm: 2932.9,
    accessStatus: "seasonal",
    sourceStatusRaw: "open,road,Seasonal",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-90',
    officialNumber: 90,
    officialName: "Longwood Forest Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 54.33,
    cumulativeFromKm: 2932.9,
    cumulativeToKm: 2987.2,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-91',
    officialNumber: 91,
    officialName: "Long Hilly Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 6.69,
    cumulativeFromKm: 2987.2,
    cumulativeToKm: 2993.9,
    accessStatus: "open",
    sourceStatusRaw: "road,open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-92',
    officialNumber: 92,
    officialName: "Tihaka Beach Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 12.88,
    cumulativeFromKm: 2993.9,
    cumulativeToKm: 3006.8,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-93',
    officialNumber: 93,
    officialName: "Oreti Beach Track",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 30.38,
    cumulativeFromKm: 3006.8,
    cumulativeToKm: 3037.2,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
  {
    id: 'te-araroa-94',
    officialNumber: 94,
    officialName: "Invercargill to Bluff",
    kind: 'main',
    travelMode: 'foot',
    countsTowardTrailDistance: true,
    relatedSectionId: null,
    matchConfidence: null,
    officialDistanceKm: 36.03,
    cumulativeFromKm: 3037.2,
    cumulativeToKm: 3073.2,
    accessStatus: "open",
    sourceStatusRaw: "open",
    bypassReason: null,
    tidalDependent: false,
  },
];

export const SECTION_REGION_SEEDS: SectionRegionSeed[] = [
  { sectionId: 'te-araroa-01', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-02', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-03', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-04', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-05', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-06', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-07', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-08', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-09', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-10', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-11', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-12', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-13', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-14', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-15', regionId: 'northland', isPrimary: true },
  { sectionId: 'te-araroa-16', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-17', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-17', regionId: 'northland', isPrimary: false },
  { sectionId: 'te-araroa-18', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-19', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-20', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-21', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-22', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-23', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-24', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-25', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-26', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-27', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-28', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-29', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-30', regionId: 'auckland', isPrimary: true },
  { sectionId: 'te-araroa-30', regionId: 'waikato', isPrimary: false },
  { sectionId: 'te-araroa-31', regionId: 'waikato', isPrimary: true },
  { sectionId: 'te-araroa-32', regionId: 'waikato', isPrimary: true },
  { sectionId: 'te-araroa-33', regionId: 'waikato', isPrimary: true },
  { sectionId: 'te-araroa-34', regionId: 'waikato', isPrimary: true },
  { sectionId: 'te-araroa-35', regionId: 'waikato', isPrimary: true },
  { sectionId: 'te-araroa-36', regionId: 'waikato', isPrimary: true },
  { sectionId: 'te-araroa-37', regionId: 'waikato', isPrimary: true },
  { sectionId: 'te-araroa-38', regionId: 'waikato', isPrimary: true },
  { sectionId: 'te-araroa-39', regionId: 'waikato', isPrimary: true },
  { sectionId: 'te-araroa-40', regionId: 'waikato', isPrimary: true },
  { sectionId: 'te-araroa-41', regionId: 'waikato', isPrimary: true },
  { sectionId: 'te-araroa-42', regionId: 'waikato', isPrimary: true },
  { sectionId: 'te-araroa-43', regionId: 'waikato', isPrimary: true },
  { sectionId: 'te-araroa-44', regionId: 'whanganui', isPrimary: true },
  { sectionId: 'te-araroa-45', regionId: 'whanganui', isPrimary: true },
  { sectionId: 'te-araroa-46', regionId: 'whanganui', isPrimary: true },
  { sectionId: 'te-araroa-47', regionId: 'whanganui', isPrimary: true },
  { sectionId: 'te-araroa-48', regionId: 'whanganui', isPrimary: true },
  { sectionId: 'te-araroa-49', regionId: 'whanganui', isPrimary: true },
  { sectionId: 'te-araroa-50', regionId: 'whanganui', isPrimary: true },
  { sectionId: 'te-araroa-51', regionId: 'whanganui', isPrimary: true },
  { sectionId: 'te-araroa-51', regionId: 'manawatu', isPrimary: false },
  { sectionId: 'te-araroa-52', regionId: 'manawatu', isPrimary: true },
  { sectionId: 'te-araroa-53', regionId: 'manawatu', isPrimary: true },
  { sectionId: 'te-araroa-54', regionId: 'manawatu', isPrimary: true },
  { sectionId: 'te-araroa-55', regionId: 'wellington', isPrimary: true },
  { sectionId: 'te-araroa-56', regionId: 'wellington', isPrimary: true },
  { sectionId: 'te-araroa-57', regionId: 'wellington', isPrimary: true },
  { sectionId: 'te-araroa-58', regionId: 'wellington', isPrimary: true },
  { sectionId: 'te-araroa-59', regionId: 'wellington', isPrimary: true },
  { sectionId: 'te-araroa-60', regionId: 'wellington', isPrimary: true },
  { sectionId: 'te-araroa-61', regionId: 'wellington', isPrimary: true },
  { sectionId: 'te-araroa-62', regionId: 'wellington', isPrimary: true },
  { sectionId: 'te-araroa-63', regionId: 'wellington', isPrimary: true },
  { sectionId: 'te-araroa-64', regionId: 'wellington', isPrimary: true },
  { sectionId: 'te-araroa-65', regionId: 'wellington', isPrimary: true },
  { sectionId: 'te-araroa-66', regionId: 'marlborough', isPrimary: true },
  { sectionId: 'te-araroa-67', regionId: 'marlborough', isPrimary: true },
  { sectionId: 'te-araroa-68', regionId: 'marlborough', isPrimary: true },
  { sectionId: 'te-araroa-69', regionId: 'tasman', isPrimary: true },
  { sectionId: 'te-araroa-70', regionId: 'marlborough', isPrimary: true },
  { sectionId: 'te-araroa-70', regionId: 'canterbury', isPrimary: false },
  { sectionId: 'te-araroa-71', regionId: 'otago', isPrimary: true },
  { sectionId: 'te-araroa-72', regionId: 'canterbury', isPrimary: true },
  { sectionId: 'te-araroa-73', regionId: 'canterbury', isPrimary: true },
  { sectionId: 'te-araroa-74', regionId: 'otago', isPrimary: true },
  { sectionId: 'te-araroa-75', regionId: 'canterbury', isPrimary: true },
  { sectionId: 'te-araroa-76', regionId: 'otago', isPrimary: true },
  { sectionId: 'te-araroa-77', regionId: 'canterbury', isPrimary: true },
  { sectionId: 'te-araroa-78', regionId: 'canterbury', isPrimary: true },
  { sectionId: 'te-araroa-79', regionId: 'canterbury', isPrimary: true },
  { sectionId: 'te-araroa-80', regionId: 'canterbury', isPrimary: true },
  { sectionId: 'te-araroa-80', regionId: 'otago', isPrimary: false },
  { sectionId: 'te-araroa-81', regionId: 'otago', isPrimary: true },
  { sectionId: 'te-araroa-82', regionId: 'otago', isPrimary: true },
  { sectionId: 'te-araroa-83', regionId: 'otago', isPrimary: true },
  { sectionId: 'te-araroa-84', regionId: 'otago', isPrimary: true },
  { sectionId: 'te-araroa-85', regionId: 'southland', isPrimary: true },
  { sectionId: 'te-araroa-86', regionId: 'otago', isPrimary: true },
  { sectionId: 'te-araroa-87', regionId: 'southland', isPrimary: true },
  { sectionId: 'te-araroa-87', regionId: 'otago', isPrimary: false },
  { sectionId: 'te-araroa-88', regionId: 'southland', isPrimary: true },
  { sectionId: 'te-araroa-89', regionId: 'southland', isPrimary: true },
  { sectionId: 'te-araroa-90', regionId: 'southland', isPrimary: true },
  { sectionId: 'te-araroa-91', regionId: 'southland', isPrimary: true },
  { sectionId: 'te-araroa-92', regionId: 'southland', isPrimary: true },
  { sectionId: 'te-araroa-93', regionId: 'southland', isPrimary: true },
  { sectionId: 'te-araroa-94', regionId: 'southland', isPrimary: true },
];
